tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "lyft/formulae"
tap "mas-cli/tap"
brew "awscli"
brew "bat"
brew "diff-so-fancy"
brew "jpeg"
brew "lame"
brew "ffmpeg"
brew "gcc"
brew "icdiff"
brew "imagemagick"
brew "imageoptim-cli"
brew "jq"
brew "mas"
brew "node"
brew "nvm"
brew "php"
brew "pidcat"
brew "postgresql"
brew "ruby-build"
brew "rbenv"
brew "rbenv-bundler"
brew "redis"
brew "tig"
brew "tmux"
brew "trace2html"
brew "watchman"
brew "yarn"
brew "youtube-dl"
brew "lyft/formulae/set-simulator-location"
cask "android-studio"
cask "battle-net"
cask "bitwarden"
cask "box-drive"
cask "caprine"
cask "colorpicker-skalacolor"
cask "cyberduck"
cask "daisydisk"
cask "diffmerge"
cask "dropbox"
cask "duet"
cask "eloston-chromium"
cask "epic-games"
cask "firefox"
cask "flipper"
cask "font-fira-code"
cask "google-hangouts"
cask "imagealpha"
cask "imageoptim"
cask "insomnia"
cask "iterm2"
cask "karabiner-elements"
cask "nosleep"
cask "notion"
cask "openemu"
cask "oversight"
cask "paw"
cask "postgres"
cask "principle"
cask "provisionql"
cask "psequel"
cask "rectangle"
cask "santa"
cask "slack"
cask "spotify"
cask "spotify-notifications"
cask "steam"
cask "sublime-text"
cask "the-unarchiver"
cask "trailer"
cask "transmission"
cask "tunnelblick"
cask "vagrant-manager"
cask "vlc"
cask "vscodium"
cask "zeplin"
mas "Brightness Slider", id: 456624497
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "iMovie", id: 408981434
mas "Ka-Block!", id: 1335413823
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "uBlock", id: 1385985095
mas "Xcode", id: 497799835
