tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "lyft/formulae"
tap "mas-cli/tap"
tap "robotsandpencils/made"
tap "wix/brew"
brew "aria2"
brew "bat"
brew "carthage", link: false
brew "diff-so-fancy"
brew "gradle"
brew "jpeg"
brew "lame"
brew "ffmpeg"
brew "gcc"
brew "icdiff"
brew "imagemagick"
brew "jq"
brew "mas"
brew "node"
brew "nvm"
brew "packer"
brew "php"
brew "pidcat"
brew "postgresql"
brew "ruby-build"
brew "rbenv"
brew "rbenv-bundler"
brew "redis"
brew "rust"
brew "rustup-init"
brew "swiftformat", link: false
brew "swiftlint", link: false
brew "tig"
brew "tmux"
brew "watchman"
brew "yarn"
brew "youtube-dl"
brew "lyft/formulae/set-simulator-location"
brew "robotsandpencils/made/xcodes"
brew "wix/brew/applesimutils"
cask "android-studio"
cask "battle-net"
cask "bitwarden"
cask "box-drive"
cask "caprine"
cask "diffmerge"
cask "dropbox"
cask "duet"
cask "eloston-chromium"
cask "epic-games"
cask "firefox"
cask "flipper"
cask "font-fira-code"
cask "imagealpha"
cask "imageoptim"
cask "insomnia"
cask "iterm2"
cask "karabiner-elements"
cask "nosleep"
cask "obinskit"
cask "openemu"
cask "oversight"
cask "principle"
cask "provisionql"
cask "rectangle"
cask "slack"
cask "spotify"
cask "steam"
cask "sublime-text"
cask "the-unarchiver"
cask "trailer"
cask "transmission"
cask "tunnelblick"
cask "visual-studio-code"
cask "vlc"
cask "zeplin"
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "iMovie", id: 408981434
mas "Ka-Block!", id: 1335413823
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541

